FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY package-lock.json ./
RUN npm ci --only=production --legacy-peer-deps
COPY prisma ./prisma/
RUN npx prisma generate
CMD ["npx", "prisma", "migrate", "deploy"]
